nelmio_api_doc:
    documentation:
        info:
            title: Splitpay Desafio API
            description: Documentação da API REST do Desafio de Dev Junior
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ]
